services:
  user-db:
    image: postgres:17
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - microservices-net
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  user-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://user-db:5432/user
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: rA41g0rqqOqgneiRlr+0hIzS5yz6rLsBtU+4sT8fJmg=
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true

volumes:
  user-db-data:
