services:
  auth-db:
    image: postgres:17
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - microservices-net
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  auth-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://auth-db:5432/auth
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: rA41g0rqqOqgneiRlr+0hIzS5yz6rLsBtU+4sT8fJmg=
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  auth-db-data:
